name: Presubmit tests
on: [push, pull_request]
jobs:
  code_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install golint
        run: |
          go get -u golang.org/x/lint/golint

      - name: Validate code
        run: |
          ./ci/gocheck.sh
          go test -cpu=2 -race -v ./...
